language: php

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

matrix:
  fast_finish: true
  include:
    - php: '7.4'
      env: SNIFF=1

script:
  # Search for PHP syntax errors.
  - find -L . -path ./vendor -prune -o -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
  # Run PHPCS.
  - if [[ "$SNIFF" == "1" ]]; then vendor/bin/phpcs . ; fi